### ISSUE TITLE
Problem a vulsrepo-server down

### ISSUE THREAD

**Issue by nakacya** [usiusi360/vulsrepo#54]
Vulsrepo-server suddenly stops
Unknown when to stop

Log
------------------------------------------------------------------------------------------------
2017/09/05 15:38:49 main.go:174: /
2017/09/05 15:38:49 main.go:174: /plugins/jquery-ui/jquery-ui.min.css
2017/09/05 15:38:49 main.go:174: /plugins/bootstrap/css/bootstrap.min.css
2017/09/05 15:38:49 main.go:174: /plugins/dynatree.js/skin-vista/ui.dynatree.css
2017/09/05 15:38:50 main.go:174: /plugins/datatables/datatables.min.css
2017/09/05 15:38:50 main.go:174: /plugins/pivot.js/pivot.min.css
2017/09/05 15:38:50 main.go:174: /plugins/bootstrapSwitch/bootstrap-switch.min.css
2017/09/05 15:38:50 main.go:174: /plugins/bootstrap-drawer/css/bootstrap-drawer.min.css
2017/09/05 15:38:50 main.go:174: /plugins/bootstrap-vertical-tabs/bootstrap.vertical-tabs.min.css
2017/09/05 15:38:50 main.go:174: /plugins/c3.js/c3.min.css
2017/09/05 15:38:50 main.go:174: /plugins/colorbox/colorbox.css
2017/09/05 15:38:50 main.go:174: /dist/css/index.css
2017/09/05 15:38:50 main.go:174: /plugins/jquery/jquery-3.2.0.min.js
2017/09/05 15:38:50 main.go:174: /plugins/bootstrap/fonts/glyphicons-halflings-regular.woff2
2017/09/05 15:38:50 main.go:174: /plugins/pathseg/pathseg.js
2017/09/05 15:38:50 main.go:174: /plugins/jquery-ui/jquery-ui.min.js
2017/09/05 15:38:50 main.go:174: /plugins/jquery.ui.touch-punch/jquery.ui.touch-punch.min.js
2017/09/05 15:38:50 main.go:174: /plugins/bootstrap/js/bootstrap.min.js
2017/09/05 15:38:50 main.go:174: /plugins/bootstrapSwitch/bootstrap-switch.min.js
2017/09/05 15:38:50 main.go:174: /plugins/pivot.js/pivot.min.js
2017/09/05 15:38:50 main.go:174: /plugins/d3.js/d3.min.js
2017/09/05 15:38:50 main.go:174: /plugins/c3.js/c3.min.js
2017/09/05 15:38:50 main.go:174: /plugins/pivot.js/d3_renderers.min.js
2017/09/05 15:38:50 main.go:174: /plugins/pivot.js/c3_renderers.min.js
2017/09/05 15:38:50 main.go:174: /plugins/jquery.xdomainajax/jquery.xdomainajax.js
2017/09/05 15:38:50 main.go:174: /plugins/dynatree.js/jquery.dynatree.min.js
2017/09/05 15:38:50 main.go:174: /plugins/jquery.blockUI/jquery.blockUI.js
2017/09/05 15:38:50 main.go:174: /plugins/bootstrap-drawer/js/drawer.min.js
2017/09/05 15:38:50 main.go:174: /plugins/datatables/datatables.min.js
2017/09/05 15:38:50 main.go:174: /plugins/jquery.balloon/jquery.balloon.min.js
2017/09/05 15:38:50 main.go:174: /plugins/colorbox/jquery.colorbox-min.js
2017/09/05 15:38:50 main.go:174: /plugins/clipboard.js/clipboard.min.js
2017/09/05 15:38:50 main.go:174: /plugins/underscore.js/underscore-min.js
2017/09/05 15:38:51 main.go:174: /plugins/lz-string/lz-string.min.js
fatal error: concurrent map writes

goroutine 451 [running]:
runtime.throw(0x709017, 0x15)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42020fad0 sp=0xc42020fab0
runtime.mapassign(0x6aeee0, 0xc420015290, 0xc42020fbf0, 0x1)
        /usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc42020fb70 sp=0xc42020fad0
github.com/usiusi360/vulsrepo/server/vendor/github.com/abbot/go-http-auth.(*DigestAuth).RequireAuth(0xc420060420, 0x83c2a0, 0xc420107960, 0xc420138000)
        /root/go/src/github.com/usiusi360/vulsrepo/server/vendor/github.com/abbot/go-http-auth/digest.go:91 +0xcc fp=0xc42020fc40 sp=0xc42020fb70
github.com/usiusi360/vulsrepo/server/vendor/github.com/abbot/go-http-auth.(*DigestAuth).Wrap.func1(0x83c2a0, 0xc420107960, 0xc420138000)

**Comment by jstangroome** [comment]
I have experienced the same issue:
```
Mar 15 21:54:04 vuls vulsrepo-server[30717]: 2018/03/15 21:54:04 main.go:202: /plugins/c3.js/c3.min.css
Mar 15 21:54:04 vuls vulsrepo-server[30717]: fatal error: concurrent map writes
Mar 15 21:54:04 vuls vulsrepo-server[30717]: goroutine 103 [running]:
Mar 15 21:54:04 vuls vulsrepo-server[30717]: runtime.throw(0x71d3d4, 0x15)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420381ad0 sp=0xc420381ab0
Mar 15 21:54:04 vuls vulsrepo-server[30717]: runtime.mapassign(0x6c1a20, 0xc42005f230, 0xc420381bf0, 0x1)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc420381b70 sp=0xc420381ad0
Mar 15 21:54:04 vuls vulsrepo-server[30717]: github.com/usiusi360/vulsrepo/server/vendor/github.com/abbot/go-http-auth.(*DigestAuth).RequireAuth(0xc420012480, 0x858560, 0xc4203dd420, 0xc4203fb900)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /root/go/src/github.com/usiusi360/vulsrepo/server/vendor/github.com/abbot/go-http-auth/digest.go:91 +0xcc fp=0xc420381c40 sp=0xc420381b70
Mar 15 21:54:04 vuls vulsrepo-server[30717]: github.com/usiusi360/vulsrepo/server/vendor/github.com/abbot/go-http-auth.(*DigestAuth).Wrap.func1(0x858560, 0xc4203dd420, 0xc4203fb900)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /root/go/src/github.com/usiusi360/vulsrepo/server/vendor/github.com/abbot/go-http-auth/digest.go:220 +0x95 fp=0xc420381ca8 sp=0xc420381c40
Mar 15 21:54:04 vuls vulsrepo-server[30717]: net/http.HandlerFunc.ServeHTTP(0xc4200b2d40, 0x858560, 0xc4203dd420, 0xc4203fb900)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc420381cd0 sp=0xc420381ca8
Mar 15 21:54:04 vuls vulsrepo-server[30717]: net/http.(*ServeMux).ServeHTTP(0x8841c0, 0x858560, 0xc4203dd420, 0xc4203fb900)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/net/http/server.go:2238 +0x130 fp=0xc420381d10 sp=0xc420381cd0
Mar 15 21:54:04 vuls vulsrepo-server[30717]: net/http.serverHandler.ServeHTTP(0xc42008c2c0, 0x858560, 0xc4203dd420, 0xc4203fb900)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/net/http/server.go:2568 +0x92 fp=0xc420381d58 sp=0xc420381d10
Mar 15 21:54:04 vuls vulsrepo-server[30717]: net/http.(*conn).serve(0xc4200e45a0, 0x858b60, 0xc4203bd880)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/net/http/server.go:1825 +0x612 fp=0xc420381fc8 sp=0xc420381d58
Mar 15 21:54:04 vuls vulsrepo-server[30717]: runtime.goexit()
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420381fd0 sp=0xc420381fc8
Mar 15 21:54:04 vuls vulsrepo-server[30717]: created by net/http.(*Server).Serve
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/net/http/server.go:2668 +0x2ce
Mar 15 21:54:04 vuls vulsrepo-server[30717]: goroutine 1 [IO wait]:
Mar 15 21:54:04 vuls vulsrepo-server[30717]: net.runtime_pollWait(0x7f6ce1718010, 0x72, 0x855ba0)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/runtime/netpoll.go:164 +0x59
Mar 15 21:54:04 vuls vulsrepo-server[30717]: net.(*pollDesc).wait(0xc42004e308, 0x72, 0x852588, 0xc4203e14e0)
Mar 15 21:54:04 vuls vulsrepo-server[30717]: /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
Mar 15 21:54:04 vuls systemd[1]: vulsrepo.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

Seems to be related to this issue in the go-http-auth library:
https://github.com/abbot/go-http-auth/issues/52
